### ISSUE TITLE
Login callback() issue

### ISSUE THREAD

**Issue by macci10** [xmartlabs/react-native-line#11]
Àfter line login when I call function of any other library's NativeModule this error occurs. Like calling the signin function of googleplus library.
![screenshot_1522062268](https://user-images.githubusercontent.com/12229782/37903124-3ce32ba2-3110-11e8-8f12-3c69589afd33.png)

**Comment by santiagofm** [comment]
Mmm i'll take a look, i think it's an issue with our android implementation itself rather than a collision with the google library.

**Comment by youraleangseng** [comment]
i have the same problem. getting error on call back

**Comment by eb16** [comment]
Hey! Sorry for the late response. I will be closing this issue since this should be addressed with the new release 🎉 
Old version is deprecated.

Please check:
https://github.com/xmartlabs/react-native-line/issues/31#issuecomment-651926931

If the error persist, please open a new issue and we will be glad to fix it as soon as possible.
Thanks!
