### ISSUE TITLE
'LineSDK/LineSDK.h' file not found

### ISSUE THREAD

**Issue by youraleangseng** [xmartlabs/react-native-line#17]
<img width="1440" alt="screen shot 2018-07-03 at 9 09 27 am" src="https://user-images.githubusercontent.com/19517411/42194984-e6d03118-7ea0-11e8-95a6-f5569d96cef5.png">

**Comment by kchalermsook** [comment]
I face the same issue. Any update?

**Comment by arsomjin** [comment]
For me. By following the Line's iOS integration guide, I face the same issue when download SDK manually (without using cocoapods). After using Cocoapods, everything is fine.

**Comment by oxygenyoyo2** [comment]
@arsomjin you save my life :) your solution work for me

**Comment by eb16** [comment]
Hey! Sorry for the late response. I will be closing this issue since this should be addressed with the new release 🎉 
Old version is deprecated, and you don't need to import frameworks for iOS app. Autolinking from 0.61 should do it automatically.

Please check:
https://github.com/xmartlabs/react-native-line/issues/31#issuecomment-651926931

If the error persist, please open a new issue and we will be glad to fix it as soon as possible.
Thanks!
