### ISSUE TITLE
Error build android

### ISSUE THREAD

**Issue by tranthuc1912** [xmartlabs/react-native-line#24]
error: no suitable method found for getLoginIntent(Context,String)
            Intent intent = LineLoginApi.getLoginIntent(context, channelId);
                                        ^
    method LineLoginApi.getLoginIntent(Context,String,LineAuthenticationParams) is not applicable
      (actual and formal argument lists differ in length)
    method LineLoginApi.getLoginIntent(Context,LineAuthenticationConfig,LineAuthenticationParams) is not applicable
      (actual and formal argument lists differ in length)
/home/thuc/Desktop/fukuon/node_modules/react-native-line-sdk/android/src/main/java/com/xmartlabs/lineloginmanager/LineLogin.java:135: error: cannot find symbol
        result.putString("accessToken", accessToken.getAccessToken());
                                                   ^
  symbol:   method getAccessToken()
  location: variable accessToken of type LineAccessToken
2 errors

**Comment by UChill** [comment]
Found that login() function on LineLogin.java call

>  LineLoginApi.getLoginIntent(context, channelId) 

which is the 4.0.x version of LIneAPI

for version 5.0.x getLoginIntent did changed parameter to 

> getLoginIntent(Context,String,LineAuthenticationParams)

but I don't know where to find LineAuthenticationParams. So.... update lib please.

**Comment by UChill** [comment]
> error: no suitable method found for getLoginIntent(Context,String)
> Intent intent = LineLoginApi.getLoginIntent(context, channelId);
> ^
> method LineLoginApi.getLoginIntent(Context,String,LineAuthenticationParams) is not applicable
> (actual and formal argument lists differ in length)
> method LineLoginApi.getLoginIntent(Context,LineAuthenticationConfig,LineAuthenticationParams) is not applicable
> (actual and formal argument lists differ in length)
> /home/thuc/Desktop/fukuon/node_modules/react-native-line-sdk/android/src/main/java/com/xmartlabs/lineloginmanager/LineLogin.java:135: error: cannot find symbol
> result.putString("accessToken", accessToken.getAccessToken());
> ^
> symbol: method getAccessToken()
> location: variable accessToken of type LineAccessToken
> 2 errors

I've made changed to LineLogin.java and it's successfully build for me.

import 3 more additional lib

> import com.linecorp.linesdk.Scope;
> import com.linecorp.linesdk.auth.LineAuthenticationParams;
> import java.util.Arrays;

then add new LineAuthenticationParams variable and pass to getLoginIntent to the login()

> LineAuthenticationParams authenticationParams = new LineAuthenticationParams.Builder().scopes(Arrays.asList(Scope.PROFILE)).build();
>             Intent intent = LineLoginApi.getLoginIntent(context, channelId, authenticationParams);

one more change due to no getAccessToken() error. So, I've changed the accessToken line in parseAccessToken(..) method to 

> result.putString("accessToken", accessToken.getTokenString());

**Comment by eb16** [comment]
Hey! Sorry for the late response. I will be closing this issue since this should be addressed with the new release 🎉 
Old version is deprecated, but contains the changes that @UChill did for the previuos version (thanks for that! 😄 )

Please check:
https://github.com/xmartlabs/react-native-line/issues/31#issuecomment-651926931

If the error persist, please open a new issue and we will be glad to fix it as soon as possible.
Thanks!
