### ISSUE TITLE
LineSDK/LineSDK.h' file not found

### ISSUE THREAD

**Issue by vyasishanatc194** [xmartlabs/react-native-line#28]
Without Import that file, I can not build.

If Removed library from this then I can build my project

![Screenshot 2019-08-05 at 5 21 27 PM](https://user-images.githubusercontent.com/5519279/62462676-9b082580-b7a5-11e9-9810-9eeb59417adf.png)

if I do this, then I can not use LineLoginManager from LineLogin.js file.
it says that LineLoginManager is undefined. 

I tried manually Link LindSdk framework, LineSDK pod file also.

if I do Link with libraries libLinaManager.a file 
then I get this error 
![Screenshot 2019-08-05 at 5 24 29 PM](https://user-images.githubusercontent.com/5519279/62462828-0a7e1500-b7a6-11e9-86a1-be1879ced113.png)

**Comment by shroukkhan** [comment]
i am having same issue on react-native 0.60.4 . did you figure this out?

**Comment by kapookchang** [comment]
Try 
```
https://github.com/elmotan95/react-native-line/pull/1/files
```

**Comment by kapookchang** [comment]
[https://github.com/elmotan95/react-native-line/pull/1/files](url)

**Comment by eb16** [comment]
Hey! Sorry for the late response. I will be closing this issue since this should be addressed with the new release. Old version is deprecated.

Please check:
https://github.com/xmartlabs/react-native-line/issues/31#issuecomment-651926931

If the error persist, please open a new issue and we will be glad to fix it as soon as possible.
Thanks!
