### ISSUE TITLE
if ([shared canLoginWithLineApp])

### ISSUE THREAD

**Issue by vyasishanatc194** [xmartlabs/react-native-line#29]
In IOS, Line Login not working with Native Line APP.

is there any way set canLoginWithLineApp in App anywhere?

**Comment by eb16** [comment]
Hey! Sorry for the late response. I will be closing this issue since this should be addressed with the new release. Old version is deprecated.

Please check:
https://github.com/xmartlabs/react-native-line/issues/31#issuecomment-651926931

If the error persist, please open a new issue and we will be glad to fix it as soon as possible.
Thanks!
