### ISSUE TITLE
How to get raw id token string for iOS?

### ISSUE THREAD

**Issue by abcde1499** [xmartlabs/react-native-line#42]
Hi,

I'm currently using
* react native: 0.59.10
* LineSDK for iOS (Objective C): 5.0.2
by manually installation.

I can't find anywhere to get the **raw id token** in LineSDKJSONWebToken class.
But I do able to get my email from credential.IDToken.email

Is there a way to get the **raw id token** string in iOS?

Thank you guys.

**Comment by eb16** [comment]
Hey! Sorry for the late response. I will be closing this issue since this should be addressed with the new release 🎉 
Old version is deprecated.

Please check:
https://github.com/xmartlabs/react-native-line/issues/31#issuecomment-651926931

By following the default example, you should get a response containing the `accessToken`.

If the error persist, please open a new issue so this issue is associated with the new version. We will be glad to fix it as soon as possible.
Thanks!
